var lang = {
	eng:{
		title: "QuickEyes - Features",
		welcome: "Welcome to QuickEyes!",
		menuname: "Features",
		h01: "Feature management",
		p01: "When tapping 'GET FEATURES' on QuickEyes opening screen you shall be redirected to feature management screen. That is the place where you can add new features to the game using your tokens to pay for unlocking them.",
		p02: "On the top of the screen, the amount of your tokens is shown, under that, all locked features are listed.",
		p03: "Features marked with a padlock are available and in case you have enough tokens you may unlock them.",
                p04: "Those marked with a Men-at-Work sign are unimplemented yet and under costruction. As soon as development and testing of a feature finishes it gets available with the very next update and you shall be informed about it in a notification.",
                h02: "About tokens",
                p05: "After installing QuickEyes you start with 1000 tokens. It is already enough to unlock one feature but you can decide on collecting more and be aimed at unlocking a feature more expensive. Basically you have two ways to collect more tokens.",
                p06: "First and best way is to play or bet and win. When winning a game or a bet you are always rewarded with some tokens. It is hard to say how many you can get because it is up to your settings. The more difficult settings you apply in a game and the better result you achieve the more tokens you win.",
                p07: "The second way is for unpatient players. In the bottom of feature management screen you may see a button displaying 'WATCH AD'. By tapping it, you will be shown a short video ad for watching which you shall be rewarded with 25 tokens. Selecting this way you also support the development of the game but still I prefer you playing and winning.",
                h03: "The features",
                s01: "Background",
                p08: "By unlocking this feature you will be able to decide whether application has a dark background image which is default or a bright one.<br/><br/>Price: 1000 tokens",
                s02: "12 images",
                p09: "This feature lets you play with decks having 133 different images, containing 133 cards each one of which having 12 images on.<br/><br/>Price: 2500 tokens",
                s03: "14 images",
                p10: "This feature lets you play with decks having 183 different images, containing 183 cards each one of which having 14 images on.<br/><br/>Price: 2500 tokens",
                s04: "Custom times",
                p11: "This feature lets you set ASANYAD's minimum and maximum thinking time in a range between 1 and 99 seconds.<br/><br/>Price: 2500 tokens",
                s05: "General images",
                p12: "This feature enables the option to have cards in deck with everyday objects on them such as car, lemon or Santa.<br/><br/>Price: 3500 tokens",
                s06: "Pick animation",
                p13: "Purchasing this feature, it will be shown by animation when you or your opponent picks a card from deck.<br/><br/>Price: 3500 tokens",
                s07: "Highscores",
                p14: "Purchasing this feature, the game stores and lets you check your best results for every setting variant. You may get notified when breaking a record.<br/><br/>Price: 10000 tokens",
                s08: "Setting management",
                p15: "This feature offers you possibility to store load and edit your desired settings.<br/><br/>Price: 10000 tokens",
                s09: "Check deck",
                p16: "Purchasing this feature, you will be able to see all cards in the deck of the current game. You may also download and print them as images to play with your family or friends at a real table.<br/><br/>Price: 10000 tokens",
                s10: "Sound",
                p17: "Purchasing this, your game will be featured with music and sound effects.<br/><br/>Price: 10000 tokens",
                s11: "Time challenge",
                p18: "This feature enables a new game type in which you can play against time. Your goal is to collect all cards of the deck as fast as you can.<br/><br/>Price: 15000 tokens",
                s12: "Online challenge",
                p19: "This feature lets you play against your friend online. You may start a challenge or accept one.<br/><br/>Price: 25000 tokens",
                s13: "No ads",
                p20: "This feature offers you possibility to get rid of in-game advertisements.<br/><br/>Price: 100000 tokens",
                h04: "Scheduling",
                p21: "You might have the question:<br/>'When will all those features be available?'",
                p22: "Well, the answer is simple although not satisfying:<br/>'I cannot promise anything.'",
                p23: "Let me tell you something personal: I am father of a large family. I have a full time job. I go to university meanwhile studying software development. And the most important: My day also consists of 24 hours.",
                p24: "I really cannot provide any scheduling on features but there is one thing I can promise you: <br/>Whenever I have a little free time I will work on QuickEyes.",
                p25: "Thank you for your patiency and understanding.",
                footerText1: "Site made in Budapest, 2019",
		footerText2: "On any further information, remark or recommendation don't hesitate to contact me on asanya.d@gmail.com"
	},
	hun:{
		title: "QuickEyes - Funkciók",
		welcome: "A QuickEyes oldala",
		menuname: "Funkciók",
                h01: "Funkciókezelés",
		p01: "Mikor a QuickEyes kezdőképernyőjén a 'PLUSZ FUNKCIÓK' lehetőséget választod, a funkciókezelő képernyőre jutsz. Ez az a hely, ahol az összegyűjtött zsetonjaidért cserébe újabb funkciókat és izgalmas lehetőségeket adhatsz a játékhoz.",
		p02: "A képernyő tetején láthatod, hány zsetonod van jelenleg, alatta pedig a zárolt funkciók listáját.",
		p03: "Amennyiben elég tokennel rendelkezel, a lakattal jelölt funkciók azonnal elérhetők, és feloldhatók.",
                p04: "Azok a funkciók, melyek 'úton folyó munkák' táblával vannak jelölve, még fejlesztés alatt állnak. Amint elkészülnek, és átesnek a tesztelésen, a legközelebbi frissítéssel elérhetővé is válnak, amiről értesítést fogsz kapni.",
                h02: "A zsetonokról",
                p05: "A QuickEyes telepítésekor kiindulásnak 1000 zsetont kapsz. Ez már elegendő is egy kisebb funkció feloldásához, de dönthetsz úgy is, hogy gyűjtesz hozzá még eleget, hogy egy drágább funkció elérhetővé váljon. Alapvetően két lehetőséged van a zsetonok számának gyarapítására.",
                p06: "Az első és legjobb lehetőséged, hogy játszol, vagy fogadsz, és nyersz. Mindig zsetonokkal jutalmazlak, mikor megnyersz egy játékot, vagy egy fogadást. Azt, hogy mennyivel, nehéz megmondani, mert az nagyban függ a beállításaidtól. Minél nehezebb játékot játszol, és minél jobb eredményt érsz el, annál több zsetont kapsz.",
                p07: "A másik lehetőség a türelmetlenek számára lett kialakítva. A funkciókezelő képernyő alján a 'HIRDETÉS' gombra koppintva egy rövid reklámvideót mutatok neked, melyet ha megnézel, 25 zsetonnal jutalmazlak. Ha ezt a lehetőséget választod, azzal a játék fejlesztését is támogatod, de ennek ellenére én azt szeretném, ha játszanál, és nyernél.",
                h03: "A funkciók",
                s01: "Háttér",
                p08: "A funkció feloldásával lehetőséged nyílik eldönteni, hogy az alkalmazásod háttere az alapértelmezett sötét kép legyen, vagy egy világosabb.<br/><br/>Ár: 1000 zseton",
                s02: "12 kép",
                p09: "Lehetőséged nyílik olyan paklival játszani, melyben 133 különböző kép szerepel, 133 lap található, és minden lapon 12 kép kap helyet.<br/><br/>Ár: 2500 zseton",
                s03: "14 kép",
                p10: "Lehetőséged nyílik olyan paklival játszani, melyben 183 különböző kép szerepel, 183 lap található, és minden lapon 14 kép kap helyet.<br/><br/>Ár: 2500 zseton",
                s04: "Egyéni idő",
                p11: "ASANYAD, a gépi játékos gondolkodási idejének alsó és felső határait állíthatod tetszés szerint 1-99 másodperces tartományban.<br/><br/>Ár: 2500 zseton",
                s05: "Általános képek",
                p12: "Választhatsz olyan paklit, melyben a lapokon teljesen általános képek láthatók, mint például autó, citrom, vagy télapó.<br/><br/>Ár: 3500 zseton",
                s06: "Húzás animáció",
                p13: "Ezen funkció feloldásával a lapok animált módon kerülnek egyik, illetve másik játékoshoz.<br/><br/>Ár: 3500 zseton",
                s07: "Rekordok",
                p14: "A játék eltárolja a legjobb eredményedet minden beállítás-kombinációra. Ezeket visszanézheted, illetve jelzést kapsz, ha megdöntöd valamelyiket.<br/><br/>Price: 10000 zseton",
                s08: "Beállítás-kezelő",
                p15: "A kedvenc beállítás-kombinációidat egyedi néven elmentheted, betöltheted, módosíthatod, illetve játékot indíthatsz az adott beállításokkal.<br/><br/>Ár: 10000 zseton",
                s09: "Pakliszemle",
                p16: "Játék közben a paklira koppintva egy előugró ablakban laponként végignézheted azt, vagy egy csomagban letöltheted, és kinyomtathatod a lapokat képek formájában, hogy egy igazi asztalnál is kártyázhass a csládoddal, barátaiddal.<br/><br/>Ár: 10000 zseton",
                s10: "Hangok",
                p17: "Ezen funkció feloldásával a játékot hangeffektek és zene teszik élvezetesebbé.<br/><br/>Ár: 10000 zseton",
                s11: "Harc az idővel",
                p18: "Aktiválhatsz egy új játéktípust, melyben az idő az ellenfeled. A célod, hogy a megszokott szabályok mellett a lehető leggyorsabban gyűjtsed be az egész paklit.<br/><br/>Ár: 15000 tokens",
                s12: "Online párbaj",
                p19: "Játékot kezdeményezhetsz egy online ellenféllel, vagy elfogadhatsz egy online kihívást.<br/><br/>Ár: 25000 zseton",
                s13: "Reklámmentesség",
                p20: "Lehetőséget kapsz, hogy letiltsad a játékban megjelenő hirdetéseket.<br/><br/>Ár: 100000 zseton",
                h04: "Mikor lesz kész",
                p21: "Talán felmerül benned a kérdés:<br/>'Mikor készül el és válik elérhetővé az összes funkció?'",
                p22: "A válasz egyszerű, ám meglehet, nem kielégítő:<br/>'Semmit sem garantálhatok.'",
                p23: "Had mondjak valami személyeset: Nagycsaládos apuka vagyok. Teljes munkaidős állásom van. Mindemellett egyetemre járok, ahol szoftverfejlesztést tanulok. És a legfontosabb: Az én napom is csak 24 órából áll.",
                p24: "Tényleg nem tudok időpontokat mondani a funciók érkezésével kapcsolatosan, viszont egy dolgot megígérhetek: <br/>Amikor csak akad egy kis szabad időm, a QuickEyes-ra fogom fordítani.",
                p25: "A megértésed és türelmed köszönöm!",
                footerText1: "Az oldal Budapesten készült 2019-ben",
		footerText2: "Bármi nemű megjegyzéssel, javaslattal, vagy felmerülő kérdés esetén keress az asanya.d@gmail.com email címen"
	},
	chi:{
		title: "QuickEyes - 新功能",
		welcome: "欢迎来到 QuickEyes！",
		menuname: "新功能",
		h01: "新功能管理",
		p01: "在 QuickEyes 开始界面上点击\"获取功能\"时，您将会切换到功能管理屏幕。在这里，您可以使用代币添加新功能，以支付解锁功能的费用。",
		p02: "在屏幕的上方，您可以看到你有多少个代币。下面显示的是未解锁的新功能。",
		p03: "有锁头图案的新功能是可以使用的，只要您有足够的代币去解锁它们。",
                p04: "显示道路工程标志的三角图案还在开发中。一旦新功能完成测试，将在下一次更新中投入使用。您将会被通知。",
                h02: "关于代币",
                p05: "在您下载QuickEyes后，您将有1000个代币作为开始筹码。它已足够支付一个新功能。当然，您也可以继续收集更多的代币去解锁更贵的功能。实际上，你有两种方法去收集更多的代币。",
                p06: "第一种是最好的方法，玩或赌和赢。当您赢了或赌赢了游戏，您将得到一些代币。很难说明您可以得到多少代币，因为这取决于您的游戏设置。游戏的设置越难，您得到的成绩越好，代币也会增多。",
                p07: "第二种方法是针对不够耐心的玩家。在屏幕的下方，有一个“观看视频”的按键。当您点击它，将链接到一个短暂的广告视频。如果您观看它，您将得到25个代币。同时，您也是在支持这个游戏的开发。但是，ASANYAD希望您通过玩与赢获得代币。",
                h03: "功能",
                s01: "背景",
                p08: "解锁此功能，您可以选择背景颜色的深与浅。<br/><br/>价格：1000个代币",
                s02: "12个图案",
                p09: "此功能您能玩一副含有133张的卡牌，里面包含133种图案，每张卡牌里面有12个图案。<br/><br/>价格：2500 个代币",
                s03: "14个图案",
                p10: "此功能您能玩一副含有183张的卡牌，里面包含183种图案，每张卡牌里面有14个图案。<br/><br/>价格：2500 个代币",
                s04: "自定义",
                p11: "此功能让你设置ASANYAD思考的最低和最高的秒数，在1和99之间选择。<br/><br/>价格：2500 个代币",
                s05: "一般图像",
                p12: "此功能能提供真实图像，如：车，圣诞老人，柠檬。<br/><br/>价格：3500 个代币",
                s06: "选取动画",
                p13: "支付此功能，当您或您的对手从卡牌上挑选一张牌时，它将通过动画显示。<br/><br/>价格：3500 个代币",
                s07: "高分",
                p14: "支付此功能，任何设置游戏中，您可以保存和查看您的最佳成绩。在打破记录时，您将会收到通知。<br/><br/>价格：10000 个代币",
                s08: "设置管理",
                p15: "此功能为您提供存储下载并编辑所需的设置。<br/><br/>价格：10000 个代币",
                s09: "查看卡牌",
                p16: "支付此功能，您可以查看一副卡牌里的所有图案。您可以下载和打印您选择的图像，以便与家人或朋友在真实的餐桌上玩牌。<br/><br/>价格：10000 个代币",
                s10: "声音",
                p17: "支付此功能，您的游戏将具有音乐和声音效果。<br/><br/>价格：10000 个代币",
                s11: "与时间挑战",
                p18: "此功能启用一种新的游戏类型，您可以与时间进行游戏。你的目标是尽快地收集所有的卡牌。<br/><br/>价格：15000 个代币",
                s12: "在线挑战",
                p19: "此功能可让您在线与您的朋友进行游戏。您可以邀请挑战或接受挑战。<br/><br/>价格：25000 个代币",
                s13: "无广告",
                p20: "此功能为您提供了游戏时无广告骚扰。<br/><br/>价格: 100000 个代币",
                h04: "计划",
                p21: "您可能有疑问：<br/>\"所有这些功能何时可用？\"",
                p22: "答案很简单，尽管令人不满意：<br/>\"我不能承诺任何东西。\"",
                p23: "让我告诉您一些私事：我是一个大家庭的父亲。我有一份全职的工作。我上大学的同时学习软件开发。最重要的是：我的一天也是24小时。",
                p24: "我虽然无法提供准确的时间去开发新功能，但是，我能保证一件事。那就是只要我有一点时间，我将会继续完善QuickEyes。",
                p25: "感谢您的耐心和理解！",
                footerText1: "网站于2019年在布达佩斯建立。",
		footerText2: "如果您有任何信息，评论或建议，请随时与 asanya.d@gmail.com 联系。"
	}
};