var lang = {
	eng:{
		title: "QuickEyes - Rules",
		welcome: "Welcome to QuickEyes!",
		menuname: "Rules",
		h01: "The point of the game",
                p01: "In this game you are aimed at collecting more cards from the deck than your opponent. Depending on your settings the deck may consist of only a few or quite many (up to 183) cards.",
                p02: "Each card is decorated with different images but if you pick two random cards, for sure, they have exactly one image in common as seen in picture.",
                p03: "It is important to mention at this point that you never play twice using the same deck. I garantee every single game having a new deck that differs from any other deck you have played with before so that you can have an even better game experience.",
                h02: "How it starts",
                p04: "At the begining of the game you get a card (that is what you see at the bottom of the screen) and your opponent also gets one (that is the card at screen-top). The middle of the screen is the place for the rest of the deck having the first card facing the players.",
                h03: "What to do now",
                p05: "During all the game you are aimed at one simple thing. You have to observe your card and the card on the top of the deck and find the common image. Your opponent is doing the exact same thing checking the own card and the deck card and searching for the match. But who will be faster?",
                p06: "Once you find the common image just tap it and your reward is the card from the top of the deck. By winning the deck card, on one hand, you will have it as your own one and on the other hand, you reveal a new one on the top of the deck. Fight shall begin again. This simple but still exciting process loops until the deck is over. Then the winner is the player who managed to collect more cards during the battle.",
                h04: "What if you tap a wrong image",
                p07: "Well, try not to. Players having a wrong guess or trying to cheat shall be punished. Depending on your preferred game settings there are two ways of retribution. On a wrong tap, either you loose the deck card and it goes to your opponent or you get banned for a few seconds.",
                h05: "What if you win",
                p08: "Winners are always rewarded. QuickEyes has several locked features. By winning a game you get rewarded with tokens that you may use, once you have collected enough, to unlock those features.",
                p09: "Clicking \'Features\' you can read more about locked features.",
		footerText1: "Site made in Budapest, 2019",
		footerText2: "On any further information, remark or recommendation don't hesitate to contact me on asanya.d@gmail.com"
	},
	hun:{
		title: "QuickEyes - A játék",
		welcome: "A QuickEyes oldala!",
		menuname: "A játék",
                h01: "A játék lényege",
                p01: "A játék célja, hogy több lapot gyűjts be a pakliból, mint az ellenfeled. A pakli - a beállításoktól függően - állhat alig néhány, vagy akár egész sok lapból (legfeljebb 183-ból).",
                p02: "Minden lapot különböző apró képek díszítenek, viszont a pakli bármely két lapját összevetve azokon pontosan egy közös kép található, ahogy azt a mellékelt ábrán is láthatod.",
                p03: "Fontos megjegyezni, hogy a QuckEyes játékban sosem játszol kétszer ugyanazzal a paklival, minden egyes játékban újat kapsz, mely garantáltan eltér az összes korábbitól ezáltal is gazdagítva a játék élményét.",
                h02: "Kezdődjön",
                p04: "A játék kezdetén kapsz a pakliból egy lapot (ezt láthatod a kijelző alsó felén), az ellenfeled is kap egyet (ez van a kijelző tetején). A pakli maradék lapjai egy stócban előlappal felfelé a játéktér közepén helyezkednek el.",
                h03: "Hogyan tovább",
                p05: "A játék egésze alatt egyetlen egyszerű feladatod van. Alaposan vizsgáld meg a saját lapod, és a pakli tetején látható lapot, hogy megtaláld azt a képet, amely közös rajtuk. Az ellenfeled ugyanezt teszi a saját lapjával, illetve a pakli tetején levővel. De melyikőtök lesz a gyorsabb?",
                p06: "Ha megtaláltad a közös képet, csak érintsd meg, és a pakli felső lapja máris a tiéd. Ezzel két dolgot idézel elő: egyrészt új lap lesz a kezedben eltakarván a korábbit, másrészt a pakli egy új lapja is feltárul a játéktér közepén. A harc kezdődhet újra. Ez az egyszerű, ám mégis izgalmas folyamat ismétlődik, míg a pakli el nem fogy. Ekkor az a győztes, aki több kártyát zsebelt be a küzdelem során.",
                h04: "Ha eltéveszted a képet",
                p07: "Ha lehet, ezt ne tedd. A játékos, aki rosszul tippel, vagy csalni próbál, büntetést érdemel. Amennyiben ez az eset áll fenn, kétféle megtorlás lehetséges. Egy rossz tipp esetén vagy az ellenfél kapja a pakli tetején levő lapot, vagy - ha azt a beállítást preferálod - egy pár másodpercig nem tippelhetsz újra.",
                h05: "És ha nyersz",
                p08: "A győztesek jutalmat érdemelnek. A QuickEyes játék számos izgalmas kiegészítő funkciót tartalmaz, melyek zároltak. Amennyiben megnyersz egy játékot, jutalmul zsetonokat kapsz, melyekből ha eleget gyűjtesz össze, feloldhatod a kívánt funkciókat.",
                p09: "A 'Funkciók' menüpontra kattintva további részleteket olvashatsz erről.",
                footerText1: "Site made in Budapest, 2019",
		footerText2: "Bármi nemű megjegyzéssel, javaslattal, vagy felmerülő kérdés esetén keress az asanya.d@gmail.com email címen"
	},
	chi:{
		title: "QuickEyes - 游戏规则",
		welcome: "欢迎来到 QuickEyes！",
		menuname: "游戏规则",
                h01: "游戏的要点",
                p01: "I在这个游戏中，您的目标是比您的对手从屏幕上收集更多的卡牌。根据您的设置，卡片组可能只包含几个或相当多的（最多 183 张）卡。",
                p02: "每张卡片有着不同的图像，但如果您选择两个随机的卡片，当然，它们正好有一个图像是一样的，如图片所示。",
                p03: "值得一提地是您永远不会玩两次相同的卡片组。我保证每一个游戏都有一个新的卡片组，不同于任何其它您之前玩过的类似的游戏。这样，您就拥有有一个更好的游戏体验。",
                h02: "如何开始",
                p04: "在游戏开始时，您会得到一张牌（这是您在屏幕底部看到的），您的对手也会得到一张（即屏幕顶部的牌）。屏幕中间是卡牌组其余部分的牌面，牌面向上面对玩家。",
                h03: "现在该怎么做",
                p05: "在所有的游戏种，您的目地很简单。您必须观察您卡片上的图像和在卡片组的图像，并找到共同的图像。您的对手也正在做完全相同的事情，检查他的卡片图像和卡片组的图像，搜索共同的图像。但是，谁会更快呢？",
                p06: "一旦您找到共同的图像，只需点击它，您的奖励是得到这张卡牌。通过赢得这张卡牌，一方面，您会有它作为您新的卡牌；另一方面，你揭开了卡牌组上的新卡片。挑战将再次开始。这个简单但仍然令人兴奋的过程会一直循环下去，直到卡牌为零。然后，获胜者是在挑战中收集最多卡牌的玩家。",
                h04: "如果点击错误的图像，该怎么办",
                p07: "好吧，尽量不要。 有错误的猜测或试图作弊的玩家将受到惩罚。 根据您喜欢的游戏设置，有两种惩罚。要么，您失去卡牌，它去您的对手那里；要么，您将被暂停几秒钟。",
                h05: "如果您赢了",
                p08: "赢家总会得到奖励的。 QuickEyes具有多个锁定功能。 通过赢得游戏，您将获得代码，当您收集了足够多的代码后，便可以使用这些代码来解锁这些功能。",
                p09: "点击\"新功能\"，您可以了解更多有关锁定功能的信息。",
		footerText1: "网站于2019年在布达佩斯建立。",
		footerText2: "如果您有任何信息，评论或建议，请随时与 asanya.d@gmail.com 联系。"
	}
};