var lang = {
	eng:{
		title: "QuickEyes - Settings",
		welcome: "Welcome to QuickEyes!",
		menuname: "Settings",
		h01: "About settings",
		p01: "QuickEyes offers a wide range of changeable options that results in a colorful variety of game experience. By trying changing settings, sooner or later, you will find your preferred ones.",
		p02: "Most of possibilities are selectable by default but some of them (those marked with red color) are locked. In order to unlock and try all features you must play and win. To read more details about locked settings visit 'Features' in the menu.",
                h02: "Player types",
                p03: "First of all you can choose the type of the players. You can play against computer player, your friend on the same device, time or online friend. You also have chance to watch a battle between two computer players and bet which one is going to win and increase the number of your tokens.",
                h03: "Bet on winner",
                p04: "In case you let two computer players play against each other you have possibility to bet who will win. If your prediction happens to be correct you shall get the tokens the winner is rewarded with.",
                h04: "ASANYAD's settings",
                p05: "The computer player is ASANYAD (me) and you can also define the way how I play. You may set the speed of my thinking and it is also up to you how often I make a wrong guess.",
                h05: "Number of images",
                p06: "Changing this setting you can affect three parameters of the game. How many different images there are in the deck, how many cards the deck contains and how many images a single card has. The five possibilities are as follows:<br /><ul><li>13 cards with 4 images on them and 13 images in the deck</li><li>31 cards with 6 images on them and 31 images in the deck</li><li>57 cards with 8 images on them and 57 images in the deck</li><li>133 cards with 12 images on them and 133 images in the deck</li><li>183 cards with 14 images on them and 183 images in the deck</li></ul>",
                h06: "Image type",
                p07: "You also have possibility to select what kind of images you want to see on the cards. You have three choices each of which meaning different level of difficulty:<br /><ul><li>numbers</li><li>logic shapes</li><li>everyday objects</li></ul>",
                p08: "Changing this option you can find out which image type is the most suitable or most challenging for you.",
                h07: "Retribution type",
                p09: "When making a wrong guess you will be punished. Either the card to win goes to your opponent or you get banned from making a new guess for a few seconds. Make your choice.",
                h08: "Animations",
                p10: "QuickEyes is an easy-looking application, yet the game has two animations.",
                p11: "First one is a tick-and-cross animation which means that a green tick or a red cross flashes when making a guess showing whether it is correct or not.",
                p12: "By default, a card simply appears in its new position when a player wins it. The second animation changes this behavior and lets you see as the card is picked from the top of the deck.",
                p13: "At this point of settings you can enable or disable the two animations described above.",
                h09: "Sound settings",
                p14: "You may turn on or off the sound effects and background music in menu and in game.",
                h10: "App background",
                p15: "QuickEyes application ships with two different backgrounds, a dark and a bright one. You may select the one you prefer.",
                h11: "Advertisement settings",
                p16: "QuickEyes has built-in advertisements that happen to appear every now and then. Changing this setting you can affect how often they pop up and whether they are simple images or videos.",
                p17: "An important remark is that video advertisements help you to collect tokens for unlocking new features.",
                h12: "Language",
                p18: "This app supports three languages, English as default, Chinese and Hungarian. There is no direct way to select the preferred display language but it is selected automatically depending on the system language of your Android device.",
                footerText1: "Site made in Budapest, 2019",
		footerText2: "On any further information, remark or recommendation don't hesitate to contact me on asanya.d@gmail.com"
	},
	hun:{
		title: "QuickEyes - Opciók",
		welcome: "A QuickEyes oldala",
		menuname: "Opciók",
		h01: "A beállításokról",
		p01: "A változatos játék érdekében a QuickEyes a módosítható paraméterek széles skáláját vonultatja fel. Próbáld őket végig, és előbb-utóbb megtalálod azokat a beállításokat, melyek a legjobb játékélményt hozzák el neked.",
		p02: "A legtöbb beállítási lehetőség már a játék telepítésekor elérhető, viszont néhányuk (amelyek piros színnel vannak jelölve) zárolt. A zárolt funkciók feloldásához nem kell mást tenned, mint játszanod, és nyerned. A zárolt funkciókról részletesebben a 'Funkciók' menüpont alatt olvashatsz.",
                h02: "Játékosok",
                p03: "Mindenek előtt természetesen megválaszthatod a játékban résztvevő ellenfelek típusát. Játszhatsz a barátod ellen ugyanazon az eszköszön, játszhatsz egy gépi játékos, vagy az idő ellen, de találhatsz egy online ellenfelet is magadnak. Végső esetben akár két gépi játékos küzdelmét is végignézheted, és fogadhatsz a játék kimenetelére, hogy a zsetonjaid gyarapítsd.",
                h03: "Fogadás",
                p04: "Amennyiben két gépi játékos harcát szeretnéd végignézni, lehetőséged van fogadni a nyertesre. Ha a játék kimenetele a te tippednek megfelelően alakul, megkapod a győztesnek járó zsetonokat.",
                h04: "ASANYAD beállításai",
                p05: "A gépi játékost (ASANYAD) magamról mintáztam. Lehetőséged van megadni, hogy milyen gyorsan gondolkodom, és reagálok, valamint azt is te döntheted el, hogy milyen gyakorisággal tippelek hibásan.",
                h05: "Képek száma",
                p06: "Ezen beállítás módosítása három tényezőre van hatással, mégpedig arra, hogy összesen hány különböző kép jelenik meg a pakliban, hány lapból áll a pakli, és az egyes lapokon hány kép látható. A következő öt lehetőség közül választhatsz:<br /><ul><li>13 lap, mindegyiken 4 kép, és 13 különböző kép a pakliban</li><li>31 lap, mindegyiken 6 kép, és 31 különböző kép a pakliban</li><li>57 lap, mindegyiken 8 kép, és 57 különböző kép a pakliban</li><li>133 lap, mindegyiken 12 kép, és 133 különböző kép a pakliban</li><li>183 lap, mindegyiken 14 kép, és 183 különböző kép a pakliban</li></ul>",
                h06: "Képek típusa",
                p07: "Lehetőséged van azt is megválasztani, hogy milyen jellegű képeket szeretnél látni a lapokon. Három változat szerepel a játékban, melyek különböző nehézségi szintet garantálnak:<br /><ul><li>számok</li><li>logikai formák</li><li>általános képek</li></ul>",
                p08: "Találd meg, melyik képtípus illik hozzád legjobban, és melyik biztosítja a legizgalmasabb kihívást!",
                h07: "Megtorlás",
                p09: "Hibás tipp esetén a játékos büntetést érdemel. A beállításaidtól függően vagy az ellenfél automatikusan megkapja a pakli tetejéről a lapot, vagy a rosszul tippelő pár másodpercig nem próbálkozhat újra. A döntés a te kezedben van.",
                h08: "Animációk",
                p10: "A QuickEyes egy egyszerű kinézetű, könnyed dizájnú alkalmazás, mégis a játékban két animáció helyet kapott.",
                p11: "Az első a tippanimáció. Ez annyit tesz, hogy tipp esetén egy zöld pipa, vagy egy piros kereszt villan fel jelezvén, hogy a tipp helyes volt-e.",
                p12: "Alapesetben amikor egy lap egy játékos birtokába kerül, az egyszerűen megjelenik az új helyén. A második animáció ezt a viselkedést bírálja felül gazdagítva a játékélményt, és láthatóvá téve, miképp egy játékos elveszi a lapot.",
                p13: "A beállítások ezen részénél a fent leírt két animációt kapcsolhatod ki, illetve be.",
                h09: "Hang beállítások",
                p14: "Ki- és bekapcsolhatod a menü-, valamint játékhangokat, illetve a játékot kísérő háttérzenét.",
                h10: "Háttér stílusa",
                p15: "A QuickEyes alkalmazás két különböző stílusú háttérképpel érkezik hozzád, egy sötéttel, és egy világossal. Válaszd azt, amely a szemednek kellemesebb.",
                h11: "Hirdetések",
                p16: "A QuickEyes alkalmazás beépített reklámokat tartalmaz, melyek időről-időre felbukkannak. Lehetőséged van beállítani, milyen gyakorisággal jelenjenek meg a reklámok, illetve hogy kép vagy videó formájában.",
                p17: "Fontos megjegyezni, hogy a videó-hirdetések megtekintéséért zsetonokat kapsz jutalmul, így előbb feloldhatod a zárolt funkciókat.",
                h12: "Nyelv",
                p18: "Az alkalmazás három nyelvet támogat, magyart, kínait, és alapértelmezetten angolt. A nyelv kiválasztására nincsen direkt lehetőség, hanem az automatikusan igazodik az androidos készüléked nyelvéhez.",
                footerText1: "Az oldal Budapesten készült 2019-ben",
		footerText2: "Bármi nemű megjegyzéssel, javaslattal, vagy felmerülő kérdés esetén keress az asanya.d@gmail.com email címen"
	},
	chi:{
		title: "QuickEyes - 游戏设置",
		welcome: "欢迎来到 QuickEyes！",
		menuname: "游戏设置",
		h01: "游戏设置",
		p01: "QuickEyes 提供广泛的多变选项，可产生丰富多彩的游戏体验。通过尝试更改设置，迟早会找到您喜欢的设置。",
		p02: "在默认情况下，大多数是可选的。但是，其中一些（标记为红色的）被锁定。 为了解锁并尝试所有的新功能，您必须玩并赢。 要了解有关锁定设置的更多详细信息，请访问菜单中的\"新功能\"。",
                h02: "玩家类型",
                p03: "首先，您可以选择玩家的类型。 您可以与电脑玩家对玩，与您朋友在同一部手机对玩，与时间对玩或在线与朋友一起玩。 您还可以观看两个电脑玩家之间的对战。",
                h03: "赌谁是赢家",
                p04: "如果您让两个电脑玩家互相对抗，您就有可能下注谁会获胜。 如果您的投注正确，您将获得获胜者获得的代币。",
                h04: "ASANYAD 的设置",
                p05: "电脑玩家是ASANYAD（我），您也可以定义我玩的方式。您可以设置我的思维速度，也由您设置我出错的频率。",
                h05: "图像数量",
                p06: "更改此设置可能会影响游戏的三个参数。卡片上有多少不同的图像，卡片组包含多少张卡片，一张卡片有多少个图像。这五种可能性如下：<br /><ul><li>一副卡片组有13张卡片和13个不同图像，一张卡片有4个图像。</li><li>一副卡片组有31张卡片和31个不同图像，一张卡片有6个图像。</li><li>一副卡片组有57张卡片和57个不同图像，一张卡片有8个图像。</li><li>一副卡片组有133张卡片和133个不同图像，一张卡片有12个图像。</li><li>一副卡片组有183张卡片和183个不同图像，一张卡片有14个图像。</li></ul>",
                h06: "图像类型",
                p07: "您还可以选择您希望在卡片上看到的图像类型。您有3种选择：<br /><ul><li>数字</li><li>逻辑形状</li><li>其他</li></ul>",
                p08: "更改此选项，您可以找出哪种图像类型对您来说最适合或最具有挑战性。",
                h07: "惩罚类型",
                p09: "当做出错误的猜测时，你会受到惩罚。要么是卡片给了您的对手，要么是你被暂停几秒钟后再继续游戏。",
                h08: "动画设置",
                p10: "QuickEyes 是一个外观简单的应用程序，此游戏有2种动画。",
                p11: "第一个是打勾和错号的动画，这意味着在猜测它是否正确时，会有绿色打勾或红色错号的显示。",
                p12: "在默认的情况下，当玩家获胜时，卡片会显示在其新位置。第二个动画也会更改其行为，并允许您看到从卡片组里选取卡片。",
                p13: "此设置，您可以启用或禁用上述两个动画。",
                h09: "声音设置",
                p14: "您可以打开或者关闭在菜单和游戏的声音效果和背景音乐。",
                h10: "应用程序的背景",
                p15: "QuickEyes 有2种不同的背景图案，深色和浅色。您可以选择您喜欢的一种。",
                h11: "广告设置",
                p16: "QuickEyes 的内置广告时而发生。此设置可以更改广告弹出的频率以及选择它们是简单的图片还是视频。",
                p17: "重要的一点是视频广告帮助您收集代币以便解锁新功能。",
                h12: "语言",
                p18: "此程序支持三种语言，中文，英语和匈牙利语。根据 Android 的系统语言自动选择您使用的语种。",
                footerText1: "网站于2019年在布达佩斯建立。",
		footerText2: "如果您有任何信息，评论或建议，请随时与 asanya.d@gmail.com 联系。"
	}
};