var lang = {
	eng:{
		title: "QuickEyes - Startup",
		welcome: "Welcome to QuickEyes!",
		menuname: "Startup",
		h01: "What you see for first time",
		p01: "After installing and starting application you are asked for your nickname but only for first time. Once it has been provided (and on further startups) you can see the opening screen of QuickEyes with 6 buttons as shown in figure.",
		p02: "Some of the buttons are red meaning that features behind them are locked yet.",
		p03: "Tapping any of the buttons starts some action or navigates you to a new screen as described below. So let us see the meaning of them.",
		h02: "QUICKPLAY",
                p04: "Tapping this button a new game starts immediately based on the settings you used the last time.",
                h03: "EDIT SETTINGS AND PLAY",
                p05: "This button navigates you to the settings page where you can apply your preferred options to start a new game. Once you like your new settings you can save them in order to reuse them later. You may read more details about settings by clicking on 'Settings' in the site menu.",
                h04: "MANAGE SAVED SETTINGS",
                p06: "Selecting this option you get to the setting manager screen where all your saved settings are listed. You can edit, delete, load, or play them. You may also define a new set of settings.",
                p07: "An important remark: By default, this feature is locked and not implemented yet. To learn more about this, select 'Features' from the menu.",
                h05: "HIGHSCORES",
                p08: "Once this button is tapped you get navigated to another screen listing your highscores. You may have your highscores for any combination of settings. When you break your own record using a given set of settings you get notified about it and also highscores list gets updated.",
                p09: "Highscore management is also a locked feature in QuickEyes and it is under construction yet.",
                h06: "ABOUT GAME",
                p10: "Tapping it you are shown another screen containing the mobile version of present website. You may read these instructions any time without leaving the QuickEyes application. (Perhaps that is what you are doing at the moment.)",  
                h07: "GET FEATURES",
                p11: "This button navigates you to the feature management screen where all unlocked features are listed. You can see how many tokens you have and how many of them you need to unlock a feature. Read more about features under 'Faetures' in menu.",
                footerText1: "Site made in Budapest, 2019",
		footerText2: "On any further information, remark or recommendation don't hesitate to contact me on asanya.d@gmail.com"
	},
	hun:{
		title: "QuickEyes - Kezdet",
		welcome: "A QuickEyes oldala",
		menuname: "Kezdet",
		h01: "Mit látsz először",
		p01: "A játék telepítését és elindítását követően meg kell adnod a játékosneved, de kizárólag az első alkalommal. Amennyiben ezt megtetted - és az alkalmazás további elindításaikor - a QuickEyes kezdő képernyője fogad, mely 6 gombot tartalmaz, ahogy azt a mellékelt ábrán is láthatod.",
		p02: "A gombok közül kettő piros színű, mely azt jelenti, hogy zárolt funkció van mögötte.",
		p03: "A gombok valamelyikét megnyomva egy-egy új funkciót érhetsz el, melyekről bővebben lentebb írok. Lássuk hát!",
		h02: "GYORSJÁTÉK",
                p04: "Ez a gomb azonnali játékkezdést jelent. Az indított játékban azok a beállítások lesznek alkalmazva, melyekkel a legutóbbi alkalommal is játszottál, vagy melyet legutóbb alapértelmezettnek adtál meg.",
                h03: "JÁTÉK OPCIÓKKAL",
                p05: "Ezzel a gombbal a beállítások oldalára juthatsz, ahol az általad leginkább preferált beállításokat választhatod ki, majd indíthatod velük a játékot. Ha tetszenek az új beállításaid, elnevezheted, és elmentheted, hogy később könnyedén újra felhasználhasd őket. A beállításokról részletesebben az 'Opciók' menüpont alatt olvashatsz.",
                h04: "MENTETT BEÁLLÍTÁSOK",
                p06: "Ezen gomb a beállítás-kezelőbe navigál, ahol megtalálhatod, szerkesztheted, törölheted, betöltheted, vagy játszhatod a korábban elmentett beállításaidat. Természetesen új beállítás-készletet is létrehozhatsz.",
                p07: "Fontos megjegyezni, hogy a beállítások mentése és a beállítás-kezelő alapértelmezetten zárolt funkció, ráadásul még fejlesztés alatt áll. Erről részletesebben a 'Funkciók' menüpont alatt olvashatsz.",
                h05: "REKORDJAIM",
                p08: "Ezzel a gombbal egy új képernyőre jutsz, ahol a személyes rekordjaid vannak nyilvántartva. Minden egyes beállítás-kombinációhoz, amivel valaha nyertél egy játékot, a QuickEyes eltárolja a legjobb eredményed. Ha egyszer egy adott beállítás-kombinációhoz tartozó rekordod megdöntöd, értesítést és jutalmat kapsz, valamint a rekordok listája is frissül.",
                p09: "A rekordok menedzselése is zárolt funkció, és jelenleg fejlesztés alatt áll.",
                h06: "JÁTÉK LEÍRÁSA",
                p10: "Ezt az opciót választva egy olyan képernyő tárul fel, mely a jelenleg olvasott honlap mobil-verzióját tartalmazza. Bármikor olvashatod a jelen instrukciókat anélkül, hogy elhagynád a QuickEyes alkalmazást. (Talán éppen azt teszed.)",  
                h07: "PLUSZ FUNKCIÓK",
                p11: "A gomb megnyomásával egy lista tárul eléd, mely a játék zárolt funkcióit tartalmazza. Láthatod, hogy pillanatnyilag hány zsetonod van, és mennyire van szükséged az egyes funkciók feloldásához. A zárolt funkciókról részletesebben a 'Funkciók' menüpont alatt olvashatsz.",
                footerText1: "Az oldal Budapesten készült 2019-ben",
		footerText2: "Bármi nemű megjegyzéssel, javaslattal, vagy felmerülő kérdés esetén keress az asanya.d@gmail.com email címen"
	},
	chi:{
		title: "QuickEyes - 开始界面",
		welcome: "欢迎来到 QuickEyes！",
		menuname: "开始界面",
		h01: "您第一眼看到的界面",
		p01: "安装和启动应用程序后，系统会要求您提供昵称，只有第一次使用者才需要。一旦昵称被提供了（并在进一步的启动）您可以看到QuickEyes的开幕屏与6个按钮，如图所示。",
		p02: "某些按钮是红色的，表示它们的功能已被锁定。",
		p03: "点击任何按钮即可开始一些操作，或将您导向新屏幕，如下所述。因此，让我们看看它们的意义。",
		h02: "快速版",
                p04: "点击此按钮，新游戏将基于您最近使用的设置立即开始。",
                h03: "编辑设置和玩法",
                p05: "此按钮将导向设置界面，您可以设置您喜欢的选项并开始新游戏。如果您喜欢您的新设置，您可以保存它们，以便以后重复使用它们。您可以通过点击网站菜单中的\"设置\"来阅读有关设置更多的详细信息。",
                h04: "保存最棒设置",
                p06: "选择此选项，可以进入设置编辑器屏幕，其中列出了所有已保存的设置。您可以编辑、删除、加载或播放它们。您还可以定义一组新的设置。",
                p07: "重要的一点：在默认情况下，此功能已锁定，尚未实现。要了解有关此内容的更多详细信息，请从菜单中选择\"新功能\"。",
                h05: "最高分纪录",
                p08: "点击此按钮后，您将导向另一个屏幕，它列出您的高分。 您有在任何组合设置中获得高分的记录。 当您使用同一组设置游戏打破自己的记录时，您会收到通知，并且高分列表也会更新。",
                p09: "高分管理也是QuickEyes中的锁定功能，并且仍在构建中。",
                h06: "游戏介绍",
                p10: "点击它，您会看到另一个屏幕，其中包含当前网站的移动版本。 您可以随时阅读这些说明，而无需离开QuickEyes的应用程序。",  
                h07: "支付新功能",
                p11: "此按钮将您导向功能管理屏幕，其中列出了所有未锁定的功能。 您可以看到您有多少代码以及解锁功能需要多少代码。 在菜单的“新功能”下了解更多有关功能的信息。",
                footerText1: "网站于2019年在布达佩斯建立。",
		footerText2: "如果您有任何信息，评论或建议，请随时与 asanya.d@gmail.com 联系。"
	}
};